#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'togl'  # Must be 'togl' to match shaderapidx9 dependency

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('TOGL_DLL_EXPORT', 1)
	conf.env.append_unique('DEFINES', [
		'strncpy=use_Q_strncpy_instead',
		'_snprintf=use_Q_snprintf_instead'
	])

def build(bld):
	source = [
		'linuxwin/dx9asmvtospv.cpp',
		'linuxwin/dxabstract.cpp',
		'linuxwin/vkentrypoints.cpp',
		'linuxwin/vkcontext.cpp',
		'linuxwin/vkbuffer.cpp',
		'linuxwin/vktex.cpp',
		'linuxwin/vkfbo.cpp',
		'linuxwin/vkprogram.cpp',
		'linuxwin/vkquery.cpp',
		'asanstubs.cpp',
		'linuxwin/decompress.c'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1'
	] + bld.env.INCLUDES_SDL2

	# NDK r10e (used for Android builds) predates Vulkan and has no Vulkan
	# headers. Build scripts download Khronos Vulkan-Headers to
	# <repo>/vulkan-headers/include/ before building.
	if bld.env.DEST_OS == 'android':
		includes += ['../vulkan-headers/include']

	defines = []

	libs = ['tier0', 'tier1', 'tier2', 'vstdlib', 'mathlib']

	# Link against Vulkan loader library
	# On Android, libvulkan.so is part of the platform
	# On Linux, libvulkan.so is from the Vulkan SDK
	# On Windows, vulkan-1.lib is from the Vulkan SDK
	if bld.env.DEST_OS == 'win32':
		libs += ['vulkan-1']
	elif bld.env.DEST_OS == 'android':
		# libvulkan.so is available on Android 7.0+ (API 24+)
		# For API 21, we may need to dlopen at runtime
		libs += ['vulkan']
	elif bld.env.DEST_OS == 'darwin':
		# MoltenVK or Vulkan loader
		libs += ['MoltenVK']
	else:
		# Linux - link against libvulkan
		libs += ['vulkan']

	# Add dl for dlopen on POSIX
	if bld.env.DEST_OS != 'win32':
		libs += ['dl']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,  # Must be 'togl' to match shaderapidx9 use=[]
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
