#! /usr/bin/env python
# encoding: utf-8
# DXVK Shader API - DirectX to Vulkan translation layer

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'shaderapidxxvk'

def options(opt):
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'SHADERAPIDX_VK',
		'SHADER_DLL_EXPORT',
		'DXVK_INTEGRATED',
		'strncpy=use_Q_strncpy_instead',
		'_snprintf=use_Q_snprintf_instead',
	])

	# Allow CI/environment to point to a Vulkan SDK location
	vulkan_sdk = os.environ.get('VULKAN_SDK')
	if vulkan_sdk:
		if conf.env.DEST_OS == 'win32':
			conf.env.append_unique('INCLUDES', os.path.join(vulkan_sdk, 'Include'))
			# Pick the correct MSVC lib subdirectory
			if conf.env.DEST_CPU == 'x86':
				conf.env.append_unique('LIBPATH', os.path.join(vulkan_sdk, 'Lib', 'x86'))
			else:
				conf.env.append_unique('LIBPATH', os.path.join(vulkan_sdk, 'Lib', 'x64'))
		else:
			conf.env.append_unique('INCLUDES', os.path.join(vulkan_sdk, 'include'))
			conf.env.append_unique('LIBPATH', os.path.join(vulkan_sdk, 'lib'))

	if conf.env.DEST_OS == 'linux':
		conf.env.append_unique('DEFINES', [
			'POSIX',
			'_LINUX',
		])
	elif conf.env.DEST_OS == 'darwin':
		conf.env.append_unique('DEFINES', [
			'POSIX',
			'OSX',
			'_OSX',
		])
	elif conf.env.DEST_OS != 'win32':
		conf.env.append_unique('DEFINES', [
			'POSIX',
		])

def build(bld):
	source = [
		'dxvk_adapter.cpp',
		'dxvk_instance.cpp',
		'dxvk_device.cpp',
		'dxvk_swapchain.cpp',
		'dxvk_context.cpp',
		'dxvk_texture.cpp',
		'dxvk_buffer.cpp',
		'dxvk_shader.cpp',
		'dxvk_descriptor.cpp',
		'dxvk_renderpass.cpp',
		'dxvk_framebuffer.cpp',
		'dxvk_pipeline.cpp',
		'dxvk_cmdlist.cpp',
		'dxvk_sync.cpp',
		'dxvk_memory.cpp',
		'shaderapidxvk.cpp',
		'shadershadownxvk.cpp',
		'shaderdevicemgrdxvk.cpp',
		'colorformatdxvk.cpp',
		'hardwareconfigdxvk.cpp',
		'meshdxvk.cpp',
		'meshdxvkbase.cpp',
# 		'texturedxvk.cpp',  // TODO: ITexture interface mismatch, needs rewrite
		'vertexdecldxvk.cpp',
		'vertexshaderdxvk.cpp',
		'pixelshaderdxvk.cpp',
		'TransitionTableDxVk.cpp',
		'../../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../common',
		'../',
		'/usr/include',
	] + getattr(bld.env, 'INCLUDES_SDL2', [])

	defines = []

	libs = ['tier0','tier1','tier2','vstdlib','bitmap','mathlib']

	if bld.env.DEST_OS != 'win32':
		libs += ['SDL2']

	# Vulkan libraries
	if bld.env.DEST_OS == 'win32':
		libs += ['vulkan-1']
	else:
		libs += ['vulkan']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
