name: Build-Graphics

on:
  push:
    paths:
      - 'togles/**'
      - 'public/togles/**'
      - 'materialsystem/**'
      - 'appframework/glmdisplaydb_linuxwin.inl'
      - 'public/togl/linuxwin/glmdisplay.h'
      - '.github/workflows/build-graphics.yml'
  workflow_dispatch:

jobs:
  build-android-aarch64-graphics:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v5
    - name: Build android-aarch64
      run: |
        scripts/build-android-arm64.sh
    - uses: actions/upload-artifact@v5
      with:
        name: android-aarch64-graphics
        path: |
          /home/runner/work/source-engine-mod/android_build/lib/arm64-v8a/libtogles.so
          /home/runner/work/source-engine-mod/android_build/lib/arm64-v8a/libmaterialsystem.so
          /home/runner/work/source-engine-mod/android_build/lib/arm64-v8a/libshaderapidx9.so
          /home/runner/work/source-engine-mod/android_build/lib/arm64-v8a/libstdshader_dx9.so
        if-no-files-found: warn

  build-android-armv7a-graphics:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v5
    - name: Build android-armv7a
      run: |
        scripts/build-android-armv7a.sh
    - uses: actions/upload-artifact@v5
      with:
        name: android-armv7a-graphics
        path: |
          /home/runner/work/source-engine-mod/android_build/lib/armeabi-v7a/libtogles.so
          /home/runner/work/source-engine-mod/android_build/lib/armeabi-v7a/libmaterialsystem.so
          /home/runner/work/source-engine-mod/android_build/lib/armeabi-v7a/libshaderapidx9.so
          /home/runner/work/source-engine-mod/android_build/lib/armeabi-v7a/libstdshader_dx9.so
        if-no-files-found: warn
